services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/mysql
    networks:
      - backend_net

  api:
    build: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: no
    networks:
      - backend_net
      - frontend_net

  web:
    build: ./frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: no
    networks:
      - frontend_net

networks:
  backend_net:
    driver: bridge
  frontend_net:
    driver: bridge
    
volumes:
  db_data: